<a href="https://colab.research.google.com/github/Santiago317/AID-Tareas/blob/main/Acceso%20a%20los%20elementos%20de%20un%20array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Acceso a los elementos de un array
import numpy as np

a = np.array([[1,2,3], [4,5,6]])
print(a[1,0])
print(a[1][0])
print(a[:, 0:2])

4
4
[[1 2]
 [4 5]]


In [14]:
#Filtrado de elementos de un array


a = np.array([[1,2,3], [4,5,6]])
print(a[(a % 2 >= 1)])
print(a[(a % 2 <= 6 ) & (a > 2)])

[1 3 5]
[3 4 5 6]


In [17]:
a = np.array ([[1,2,3], [4,5,6]])
b = np.array ([[1,1,1], [2,2,2]])
print(a + b)

print(a / b)

print(a ** 2)


[[2 3 4]
 [6 7 8]]
[[1.  2.  3. ]
 [2.  2.5 3. ]]
[[ 1  4  9]
 [16 25 36]]


In [19]:
#Operaciones matematicas a nivel de array

a = np.array ([[1,2,3], [4,5,6]])
b = np.array ([[1,1], [2,2], [3,3]])

print(a.dot(b))

print(a.T)

[[14 14]
 [32 32]]
[[1 4]
 [2 5]
 [3 6]]
